CREATE DATABASE IF NOT EXISTS smart_home;
USE smart_home;

CREATE TABLE IF NOT EXISTS ruangan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_ruangan VARCHAR(100) NOT NULL,
    suhu DECIMAL(5,2) DEFAULT 0,
    kelembaban DECIMAL(5,2) DEFAULT 0,
    energi DECIMAL(10,2) DEFAULT 0,
    lampu_status BOOLEAN DEFAULT FALSE,
    pintu_status BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);